[package]
name = "oxirush-gtp-u-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
oxirush-gtp-u = { path = "..", default-features = false }

# Not part of any parent workspace.
[workspace]
members = ["."]

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false
bench = false
